name: url_shortener

services:
  postgres:
    image: postgres:16
    container_name: urlshortener-db
    env_file: [ .env ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./url-shortener-sb
    container_name: linklytics-backend
    env_file: [ .env ]
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PORT: ${PORT}

      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      APP_COOKIE_SECURE: ${APP_COOKIE_SECURE}

    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8081/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10

  # PROD frontend (nginx serving built react)
  # This is OPT-IN now; it won't run/build unless you pass --profile prod
  # frontend:
    # profiles: ["prod"]
    # build:
      # context: ./url-shortener-react
      # dockerfile: Dockerfile
      # args:
        #VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        #VITE_REDIRECT_BASE_URL: ${VITE_REDIRECT_BASE_URL}
    # container_name: linklytics-frontend
    # ports:
      # - "80:80"
    # depends_on:
      # backend:
        # condition: service_healthy

volumes:
  pgdata:
