name: url_shortener

services:
  postgres:
    image: postgres:16
    container_name: urlshortener-db
    env_file: [ .env ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

    ports:
      - "5435:5432"


  backend:
    build: ./url-shortener-sb
    container_name: linklytics-backend
    env_file: [ .env ]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      # Backend is inside docker, so it must talk to postgres service name on 5432
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PORT: ${PORT}

      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      APP_COOKIE_SECURE: ${APP_COOKIE_SECURE}

    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./url-shortener-react
      dockerfile: Dockerfile
    container_name: linklytics-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: