spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/URL_Shortener
    username: postgres
    password: 6521
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


logging:
  level:
    org.flywaydb: INFO
    org.springframework.security: INFO


frontend:
  url: http://localhost:5173

jwt:
  secret: VYqxdFGY2cnbGFRO5aKjJ2CqoOMuJBIVC9Hf7O7Il/E=

management:
  endpoints:
    web:
      exposure:
        include: health, info

app:
  cookie:
    secure: false


